### ISSUE TITLE
Critical : components orchestration is broken when loop component is used

### ISSUE THREAD

**Issue by kubik39** [langflow-ai/langflow#11009]
### Bug Description

[New Flow.json](https://github.com/user-attachments/files/24142260/New.Flow.json)

Components used to wait for all their inputs before being processed. That is not the case any more when a component loop is added in the flow.
If for example you create 2 parallels branches in flows managed by the loop, the component who agregate these 2 branches is not waiting to have both branches calculed before being processed. Result : agregation is done when one of the two branches is done. 
Impacts : we agregate data with item (related to the branch which is done) and with item N-1 (branch which was not ended when agragate components was processed)

It is a critical bug because we are limited to build complex flows as soos as a loop component is used.

### Reproduction

Look at the attached file. DataFrame Operation component is not waiting for the end of his two entries.

### Expected behavior

A component have to wait all the time to have all entries before being processed.

### Operating System

Windows 11 / Windows server 2019

### Langflow Version

1.6.9

### Python Version

3.12

### Flow File

[New Flow.json](https://github.com/user-attachments/files/24142271/New.Flow.json)

**Comment by Empreiteiro** [comment]
Fixed in branch `release-1.7.0` and main.

https://github.com/langflow-ai/langflow/pull/10305

https://github.com/langflow-ai/langflow/issues/10669

**Comment by kubik39** [comment]
In Langflow 1.7.3 this issue is still present. Bug is still present

**Comment by kubik39** [comment]
@Empreiteiro , could you please reopen this ticket ? Feel free to ask any information if required.
Regards,

**Comment by Empreiteiro** [comment]
@kubik39 Reopened for investigation.

**Comment by Empreiteiro** [comment]
@kubik39 after investigation, I identified that the PR that fixed the problem had not been merged.

It has now been merged and the fix is ​​in main : https://github.com/langflow-ai/langflow/pull/11034

**Comment by kubik39** [comment]
Thanks a lot, great news!!
