### ISSUE TITLE
Logs panel shows “No Data Available” — no component execution logs displayed

### ISSUE THREAD

**Issue by phennapa-saeliw** [langflow-ai/langflow#11135]
### Bug Description

On my self-hosted Langflow instance running via Docker, the Logs panel (Inspect component executions) consistently shows “No Data Available” and does not display any component execution logs, even after running flows/components multiple times.

<img width="3452" height="1810" alt="Image" src="https://github.com/user-attachments/assets/e41ebf90-bcbd-4691-b28f-36fb1146a1c7" />

### Reproduction

Steps to reproduce

1. Open Langflow UI
2. Create or open any flow
3. Run the flow (or run any component)
4. Open Logs panel

### Expected behavior

The Logs panel should display component execution logs (runs, status, errors, timestamps, etc.).

### Operating System

macOS

### Langflow Version

1.7.0

### Python Version

None

**Comment by AntonioABLima** [comment]
Hi @PepperYan, it looks like `1.7.0` was yanked or removed due to errors, and I couldn't find the `1.7.0` Docker tag. I'll try to reproduce this using the `1.7.1` Docker image instead.

<img width="1832" height="414" alt="Image" src="https://github.com/user-attachments/assets/3b09b4f3-5ece-4b44-92a4-1f43d867d4ea" />

**Comment by AntonioABLima** [comment]
It looks like this is happening in all environments. The error has already been identified, and there is a PR #10820 addressing it. Thanks for the report, it will be fixed soon!"

**Comment by AntonioABLima** [comment]
The fix was merged into main about 4 days ago. I tested it myself and it works fine. Just a reminder that it wasn't applied to versions 1.7.1 or 1.7.2, but it should be included in a release soon.

**Comment by phennapa-saeliw** [comment]
Thanks for the update! I’ll wait for the next release that includes the fix and will test again once it’s available.

**Comment by guna-20** [comment]
@AntonioABLima 

<img width="1856" height="954" alt="Image" src="https://github.com/user-attachments/assets/47ed6472-8f57-4a7a-80a1-f5a31bab701e" />


 i m using langflow-1.7.2 . still getting this issue.

**Comment by AntonioABLima** [comment]
> The fix was merged into main about 4 days ago. I tested it myself and it works fine. Just a reminder that it wasn't applied to versions 1.7.1 or 1.7.2, but it should be included in a release soon.

The fix hasn't been released yet.

**Comment by YeonghyeonKO** [comment]
+1

**Comment by human5810** [comment]
Hi, same behavior, no logs displayed.

**Comment by skyghost2210** [comment]
Hi again, same behavior, no logs displayer
