### ISSUE TITLE
The --pre version reports ERROR

### ISSUE THREAD

**Issue by captainst** [langflow-ai/langflow#1709]
**Describe the bug**
1. I created a new conda environment with python 3.10
2. I installed the pre version using `python -m pip install langflow --pre --force-reinstall`
3. Launch the langflow using `langflow run`
And I got the following error messages:
```
(langflow) :~$ langflow run
Starting Langflow v1.0.0a22...
[04/16/24 22:13:33] ERROR    2024-04-16 22:13:33 - ERROR    - service -          service.py:171
                             AutogenerateDiffsDetected: New upgrade operations
                             detected: [[('modify_type', None, 'apikey',
                             'created_at', {'existing_nullable': True,
                             'existing_server_default':
                             DefaultClause(<sqlalchemy.sql.elements.TextClause
                             object at 0x7f3e13347520>, for_update=False),
                             'existing_comment': None}, TIMESTAMP(),
                             DateTime(timezone=True)), ('modify_nullable', None,
                             'apikey', 'created_at', {'existing_type':
                             TIMESTAMP(), 'existing_server_default':
                             DefaultClause(<sqlalchemy.sql.elements.TextClause
                             object at 0x7f3e13347520>, for_update=False),
                             'existing_comment': None}, True, False)]]
                    ERROR    2024-04-16 22:13:33 - ERROR    - utils - Something     utils.py:51
                             went wrong running migrations. Please, run `langflow
                             migration --fix`
Shutting down Langflow...
                    ERROR    2024-04-16 22:13:33 - ERROR    - on - Traceback (most    on.py:121
                             recent call last):
                               File
                             "/opt/anaconda3/envs/langflow/lib/python3.10/site-packag
                             es/starlette/routing.py", line 732, in lifespan
                                 async with self.lifespan_context(app) as
                             maybe_state:
                               File
                             "/opt/anaconda3/envs/langflow/lib/python3.10/contextlib.
                             py", line 201, in __aenter__
                                 raise RuntimeError("generator didn't yield") from
                             None
                             RuntimeError: generator didn't yield

                    ERROR    2024-04-16 22:13:33 - ERROR    - on - Application startup on.py:59
                             failed. Exiting.
[04/16/24 22:13:33] ERROR    2024-04-16 22:13:33 - ERROR    - glogging - Worker glogging.py:272
                             (pid:557394) exited with code 3
                    ERROR    2024-04-16 22:13:33 - ERROR    - glogging -        glogging.py:272
                             Shutting down: Master
                    ERROR    2024-04-16 22:13:33 - ERROR    - glogging -        glogging.py:272
                             Reason: Worker failed to boot.
```
And I did run `langflow migration --fix`, but it did not help.

**Browser and Version**
 not reached to browser step

**To Reproduce**
Steps to reproduce the behavior: Just follow the 3 steps described above.

**Screenshots**

**Additional context**

**Comment by ogabrielluiz** [comment]
Hey @captainst 
How are you? 

We've just released a new version. Do you mind seeing if it works for you?

**Comment by captainst** [comment]
@ogabrielluiz Thank you for you help!
I tried the above steps with a new created Anaconda environment. I did notice the new Langflow version (`Starting Langflow v1.0.0a23...`). But the error persisted (with the same reported line numbers).

**Comment by ogabrielluiz** [comment]
Could you head over to your cache folder and find the langflow folder and rename the langflow.db file to something else? 

Should be `~/.cache/langflow` on Linux and `~/Library/Caches/langflow` on Mac.

**Comment by captainst** [comment]
@ogabrielluiz Magic! That seems the key. At least I see the web frontend now. I'll try to test some components to see if my setup works. For the moment, I'll close this issue as solved.
Thank you very much !
