### ISSUE TITLE
Custom component not showing in the UI

### ISSUE THREAD

**Issue by mgsotelo** [langflow-ai/langflow#5753]
### Bug Description

I am using a Langflow custom component but I can't see it in the UI. My .env  is the following: 

```bash 
LANGFLOW_LOG_LEVEL=debug
LANGFLOW_LOG_FILE='logs/langflow.log'
LANGFLOW_COMPONENTS_PATH='./components/'
```
My file structure is the following: 
```
├── components
│   └── financial
│       └── polygon_stock_graph.py
└── logs
    ├── langflow.2025-01-15_15-46-14_723977.log
    └── langflow.log

4 directories, 3 files
```

But still I can't see my component in the UI, I saw [this issue (5595)](https://github.com/langflow-ai/langflow/issues/5595) without success, solved by [this PR](https://github.com/langflow-ai/langflow/pull/5626) but it doesn't solve my issue. Any ideas?

So far, the only workaround I found is to create a Custom Component from the UI and copy/paste my python code there, but I don't think that it is an ideal scenario.

### Reproduction

1. Install Langflow version 1.1.1 and set up the application.
2. Open the Langflow UI.
3. Navigate to the Helpers menu.
4. Observe that the Custom Component option is not available.

### Expected behavior

The Helpers menu should include the Custom Component option, allowing users to drag it into the workspace and define custom components as described in the Langflow documentation.

### Who can help?

@italojohnny, @ogabrielluiz or anyone on the Full Stack team

### Operating System

macOS Sonoma Version 14.2.1 (23C71)

### Langflow Version

1.1.1

### Python Version

3.11

### Screenshot

The component is not showing in the UI, and not even its category is shown

<img width="756" alt="Image" src="https://github.com/user-attachments/assets/d1500a89-22f0-4eb9-aa96-738d9c080937" />

### Flow File

N/A

**Comment by carlosrcoelho** [comment]
Hey @mgsotelo 

Check it out this doc:
https://docs.langflow.org/components-custom-components#directory-structure-requirements

Let me know if this is what you’re looking for.

**Comment by mgsotelo** [comment]
Hi @carlosrcoelho I followed that same guide but had no results so far 😞

**Comment by anovazzi1** [comment]
hey @mgsotelo how are you? this issue was fixed before 1.1.1 by this [PR](https://github.com/langflow-ai/langflow/pull/5700) and it's already available on 1.1.2, can you please update your version and try again ?

**Comment by thamwangjun** [comment]
@anovazzi1 I am on version 1.1.3 and this bug is still an issue

**Comment by thamwangjun** [comment]
@anovazzi1 Sorry, my mistake, I somehow fixed it on 1.1.3. My Custom Component is visible now. Not sure if @mgsotelo still faces the same issue.
