### ISSUE TITLE
Headers are not being saved for MCP Server SSE

### ISSUE THREAD

**Issue by PeterHuo201** [langflow-ai/langflow#9099]
### Bug Description

When adding an MCP server as SSE, there are input fields for headers and environment variables. However, these fields are not being saved nor used. use-add-mcp-server.ts seems to leave out these fields as well.

When I put authorization bearer token in the header, the MCP server component throws 

ERROR  - mcp - Configuration error for server bookingkit: Invalid SSE URL: Server returned client error status: 401

Is this intentional or is it a bug?

### Reproduction

1. Add an MCP server as SSE either from the canvas or from the MCP server page in settings. 
2. Add your headers.
3. Add server, and when you go back to check, all these fields are gone.

### Expected behavior

Headers and environment variables are saved and used correctly.

### Operating System

mac os 15.5

### Langflow Version

1.5.0.post1

### Python Version

None

**Comment by Yukiyukiyeah** [comment]
@lucaseduoli could you help look at it?

**Comment by sfriedowitz** [comment]
I am having the same issue on both version 1.5.0.post1 and 1.5.0

**Comment by daniel-quiroga** [comment]
Please fix this!

**Comment by Yoannoza** [comment]
I have the same issue

**Comment by HiltonRosenfeld** [comment]
I have the same issue.

**Comment by lucaseduoli** [comment]
Hello!
Thanks for the report. I just fixed it on this branch:

https://github.com/langflow-ai/langflow/pull/9148

It will be released as soon as possible.

**Comment by mrburrito** [comment]
@lucaseduoli when will this be released? It's been 6 weeks and still not published. There's another open issue referencing the PR as well. https://github.com/langflow-ai/langflow/issues/9579

**Comment by luizhsalazar** [comment]
same problem in version 1.6.4!
