### ISSUE TITLE
Agents using google generative AI on open/refresh reverts the model to gemma

### ISSUE THREAD

**Issue by cuca24** [langflow-ai/langflow#9630]
### Bug Description

Agents using google generative AI on open/refresh of a flow (using f5 or CRTL+R after the flow is saved) reverts the model to gemma. 
It seems like the issue is calling the route: /custom_component/update that changes the model to gemma  (first model in the list) and returns the response with new value gemma. It seems like component is updated in functions update_component_build_config inside src/backend/base/langflow/custom/utils.py file

### Reproduction

1. Create new Agent
2. Add google generative AI 
3. Select any model that is not first in the list and save
4. Refresh the page. For a second the model that was selected in step 3 will show up and it will be changed to gemma.

### Expected behavior

After page Refresh. The model that was selected in step 3 should stay selected

### Operating System

Ubuntu 24 docker env

### Langflow Version

1.5.0-post2

### Python Version

None

### Screenshot

<img width="487" height="981" alt="Image" src="https://github.com/user-attachments/assets/49b07d01-e1e1-4248-9c5d-f888aa62ec36" />

**Comment by grider3149** [comment]
Try this one.
https://droplink.digital/file/9c170c67f45adc6b3309076d31e5df49

**Comment by Empreiteiro** [comment]
@cuca24 This error is present up to version 1.5.0post2, but it has already been fixed in main and will be working correctly in the next version.

**Comment by cuca24** [comment]
This is still not working correctly in version 1.5.1. @Empreiteiro 
Or is not in this version

**Comment by Empreiteiro** [comment]
@cuca24 The bug has been fixed in main (the most up-to-date version of the code). In the latest (1.5.0post2), the issue will still occur, so you can:

- Wait for the new release (scheduled for the next few days);
- Use main (a clone of the repository).
